### ISSUE TITLE
Use name AdvancedParticleSamplers.jl or AdvancedParticleFilters.jl?

### ISSUE THREAD

**Issue by devmotion** [TuringLang/AdvancedPS.jl#10]
The README uses the name "AdvancedParticleSamplers.jl" (so maybe that was the initial name of the repo?). IMO that's a lot more descriptive than AdvancedPS.jl, at least I wasn't familiar with the abbreviation PS (in contrast to MH or HMC with their respective packages AdvancedMH and AdvancedHMC). So maybe it could be helpful (also to make it easier to discover this package) to rename it to AdvancedParticleSamplers.jl or something like AdvancedParticleFilters.jl?

Long names shouldn't be a problem for users or developers since one could always define `const AdvancedPF = AdvancedParticleFilters` at the top of a module or script, if needed.

**Comment by yebai** [comment]
How about `AdvancedSMC`? `SMC` is a common abbreviation, similar to MH, so should be self-explanatory. The only disadvantage is that, technically, particle MCMC samplers aren't SMC methods.
