### ISSUE TITLE
Stochastic/data-dependent control flow broken 

### ISSUE THREAD

**Issue by yebai** [TuringLang/AdvancedPS.jl#37]
See [here](https://github.com/TuringLang/AdvancedPS.jl/pull/36/files#diff-adeb9cc1169e7dacb2d939910c0545cad39f379a85bc64736add26749cb4b005R62). This will be fixed in new versions of Libtask - hopefully soon. We should warn the user when making a new Turing release - [examples](https://turing.ml/dev/tutorials/06-infinite-mixture-model/) depend on this feature will return incorrect results but won't throw errors. 

Also, unbounded loops are not supported but hopefully will be fixed in Libtask soon.

**Comment by yebai** [comment]
cc @devmotion @KDr2 @FredericWantiez @cpfiffer

**Comment by cpfiffer** [comment]
Wait, what exactly is the behavior?

**Comment by KDr2** [comment]
We can throw an error if there's control flow in the task function, maybe we'd better add this to Libtkask first?

**Comment by KDr2** [comment]
> We can throw an error if there's control flow in the task function, maybe we'd better add this to Libtkask first?

Oh, I am sorry, it is not easy to predict the control flow is a dynamic one or a static one.

**Comment by yebai** [comment]
Fixed by https://github.com/TuringLang/Libtask.jl/pull/116
