### ISSUE TITLE
Libtask v0.7.4 error

### ISSUE THREAD

**Issue by FredericWantiez** [TuringLang/AdvancedPS.jl#59]
Seems like the latest release of Libtask broke something here:
https://github.com/TuringLang/AdvancedPS.jl/runs/6924872237?check_suite_focus=true

**Comment by FredericWantiez** [comment]
It's all coming from unused arguments from the models in the test suite. See [issue here](https://github.com/TuringLang/Libtask.jl/issues/148).

https://github.com/TuringLang/AdvancedPS.jl/blob/0bb8fdea519dac7558851753caf28dd2d56b5a6c/test/container.jl#L12-L21


and here:
https://github.com/TuringLang/AdvancedPS.jl/blob/0bb8fdea519dac7558851753caf28dd2d56b5a6c/test/container.jl#L140

**Comment by yebai** [comment]
Fixed by https://github.com/TuringLang/Libtask.jl/pull/149
